import { GradeConfig } from './types';

export const GRADE_CONFIGS: GradeConfig[] = [
  {
    key: 'grade_4',
    label: 'Grade 4',
    gradeRange: '4',
    ageRange: '9-10 years',
    description: 'Number system, fractions & decimals, operations & money, measurement & geometry, and patterns.',
    file: 'grade_4_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#34d399',
  },
  {
    key: 'grade_5',
    label: 'Grade 5',
    gradeRange: '5',
    ageRange: '10-11 years',
    description: 'Number system, operations & decimals, geometry & measurement, data handling & mapping, and patterns & symmetry.',
    file: 'grade_5_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#f59e0b',
  },
  {
    key: 'grade_6',
    label: 'Grade 6',
    gradeRange: '6',
    ageRange: '11-12 years',
    description: 'Number system, ratios & rates, expressions & equations, geometry, and statistics & probability.',
    file: 'grade_6_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#f97316',
  },
  {
    key: 'grade_7',
    label: 'Grade 7',
    gradeRange: '7',
    ageRange: '12-13 years',
    description: 'Number systems & integers, fractions & decimals, algebra & equations, geometry & mensuration, and data handling.',
    file: 'grade_7_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#a78bfa',
  },
  {
    key: 'grade_8',
    label: 'Grade 8',
    gradeRange: '8',
    ageRange: '13-14 years',
    description: 'Number systems & powers, algebra & linear equations, commercial math, geometry & mensuration, and data handling & probability.',
    file: 'grade_8_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#c084fc',
  },
  {
    key: 'grade_9',
    label: 'Grade 9',
    gradeRange: '9',
    ageRange: '14-15 years',
    description: 'Real numbers & polynomials, coordinate geometry & linear equations, triangles & quadrilaterals, mensuration & statistics, and probability & reasoning.',
    file: 'grade_9_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#ec4899',
  },
  {
    key: 'grade_10',
    label: 'Grade 10',
    gradeRange: '10',
    ageRange: '15-16 years',
    description: 'Real numbers, polynomials & algebra, triangles, circles & geometry, trigonometry & applications, coordinate geometry, and statistics & probability.',
    file: 'grade_10_set_normalized.json',
    enriched: true,
    icon: '',
    color: '#ef4444',
  },
];

export const QUESTIONS_PER_TEST = 15;
export const TEST_TIME_LIMIT = 600; // 10 minutes in seconds
